 FROM ubuntu:18.04

 COPY install_simple.sh /tmp/install.sh
 RUN sh /tmp/install.sh && rm /tmp/install.sh

 WORKDIR /usr/home

 COPY ./* ./

 RUN chmod u+x graph_monitor.py
 CMD ["python", "graph_monitor.py"]
